// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: proto/ticket/ticket.proto

package ticket

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BookTicketsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID     uint64   `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	ScheduleID  uint64   `protobuf:"varint,2,opt,name=ScheduleID,proto3" json:"ScheduleID,omitempty"`
	SeatType    uint64   `protobuf:"varint,3,opt,name=SeatType,proto3" json:"SeatType,omitempty"`
	PassengerID []uint64 `protobuf:"varint,4,rep,packed,name=PassengerID,proto3" json:"PassengerID,omitempty"`
}

func (x *BookTicketsRequest) Reset() {
	*x = BookTicketsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ticket_ticket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTicketsRequest) ProtoMessage() {}

func (x *BookTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTicketsRequest.ProtoReflect.Descriptor instead.
func (*BookTicketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *BookTicketsRequest) GetOrderID() uint64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *BookTicketsRequest) GetScheduleID() uint64 {
	if x != nil {
		return x.ScheduleID
	}
	return 0
}

func (x *BookTicketsRequest) GetSeatType() uint64 {
	if x != nil {
		return x.SeatType
	}
	return 0
}

func (x *BookTicketsRequest) GetPassengerID() []uint64 {
	if x != nil {
		return x.PassengerID
	}
	return nil
}

type BookTicketsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
}

func (x *BookTicketsReply) Reset() {
	*x = BookTicketsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ticket_ticket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookTicketsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTicketsReply) ProtoMessage() {}

func (x *BookTicketsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTicketsReply.ProtoReflect.Descriptor instead.
func (*BookTicketsReply) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *BookTicketsReply) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type RefundTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketID uint64 `protobuf:"varint,1,opt,name=TicketID,proto3" json:"TicketID,omitempty"`
}

func (x *RefundTicketRequest) Reset() {
	*x = RefundTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ticket_ticket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundTicketRequest) ProtoMessage() {}

func (x *RefundTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundTicketRequest.ProtoReflect.Descriptor instead.
func (*RefundTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *RefundTicketRequest) GetTicketID() uint64 {
	if x != nil {
		return x.TicketID
	}
	return 0
}

type RefundTicketReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
}

func (x *RefundTicketReply) Reset() {
	*x = RefundTicketReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ticket_ticket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundTicketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundTicketReply) ProtoMessage() {}

func (x *RefundTicketReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_ticket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundTicketReply.ProtoReflect.Descriptor instead.
func (*RefundTicketReply) Descriptor() ([]byte, []int) {
	return file_proto_ticket_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *RefundTicketReply) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

var File_proto_ticket_ticket_proto protoreflect.FileDescriptor

var file_proto_ticket_ticket_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x53, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0b, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x49, 0x44, 0x22, 0x30, 0x0a, 0x10, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x31, 0x0a, 0x13, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x22, 0x31, 0x0a, 0x11, 0x52, 0x65, 0x66, 0x75, 0x6e,
	0x64, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x99, 0x01, 0x0a, 0x06, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x45, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0c,
	0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ticket_ticket_proto_rawDescOnce sync.Once
	file_proto_ticket_ticket_proto_rawDescData = file_proto_ticket_ticket_proto_rawDesc
)

func file_proto_ticket_ticket_proto_rawDescGZIP() []byte {
	file_proto_ticket_ticket_proto_rawDescOnce.Do(func() {
		file_proto_ticket_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ticket_ticket_proto_rawDescData)
	})
	return file_proto_ticket_ticket_proto_rawDescData
}

var file_proto_ticket_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ticket_ticket_proto_goTypes = []interface{}{
	(*BookTicketsRequest)(nil),  // 0: ticket.BookTicketsRequest
	(*BookTicketsReply)(nil),    // 1: ticket.BookTicketsReply
	(*RefundTicketRequest)(nil), // 2: ticket.RefundTicketRequest
	(*RefundTicketReply)(nil),   // 3: ticket.RefundTicketReply
}
var file_proto_ticket_ticket_proto_depIdxs = []int32{
	0, // 0: ticket.Ticket.BookTickets:input_type -> ticket.BookTicketsRequest
	2, // 1: ticket.Ticket.RefundTicket:input_type -> ticket.RefundTicketRequest
	1, // 2: ticket.Ticket.BookTickets:output_type -> ticket.BookTicketsReply
	3, // 3: ticket.Ticket.RefundTicket:output_type -> ticket.RefundTicketReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ticket_ticket_proto_init() }
func file_proto_ticket_ticket_proto_init() {
	if File_proto_ticket_ticket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ticket_ticket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookTicketsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ticket_ticket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookTicketsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ticket_ticket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ticket_ticket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundTicketReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ticket_ticket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ticket_ticket_proto_goTypes,
		DependencyIndexes: file_proto_ticket_ticket_proto_depIdxs,
		MessageInfos:      file_proto_ticket_ticket_proto_msgTypes,
	}.Build()
	File_proto_ticket_ticket_proto = out.File
	file_proto_ticket_ticket_proto_rawDesc = nil
	file_proto_ticket_ticket_proto_goTypes = nil
	file_proto_ticket_ticket_proto_depIdxs = nil
}
