// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: proto/seat/seat.proto

package seat

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CountRemainingSeatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatType       uint32 `protobuf:"fixed32,1,opt,name=SeatType,proto3" json:"SeatType,omitempty"`
	TrainID        uint64 `protobuf:"fixed64,2,opt,name=TrainID,proto3" json:"TrainID,omitempty"`
	ScheduleStatus uint64 `protobuf:"fixed64,3,opt,name=ScheduleStatus,proto3" json:"ScheduleStatus,omitempty"`
}

func (x *CountRemainingSeatsRequest) Reset() {
	*x = CountRemainingSeatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seat_seat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountRemainingSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRemainingSeatsRequest) ProtoMessage() {}

func (x *CountRemainingSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seat_seat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRemainingSeatsRequest.ProtoReflect.Descriptor instead.
func (*CountRemainingSeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_seat_seat_proto_rawDescGZIP(), []int{0}
}

func (x *CountRemainingSeatsRequest) GetSeatType() uint32 {
	if x != nil {
		return x.SeatType
	}
	return 0
}

func (x *CountRemainingSeatsRequest) GetTrainID() uint64 {
	if x != nil {
		return x.TrainID
	}
	return 0
}

func (x *CountRemainingSeatsRequest) GetScheduleStatus() uint64 {
	if x != nil {
		return x.ScheduleStatus
	}
	return 0
}

type CountRemainingSeatsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number uint32 `protobuf:"fixed32,1,opt,name=Number,proto3" json:"Number,omitempty"`
}

func (x *CountRemainingSeatsReply) Reset() {
	*x = CountRemainingSeatsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seat_seat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountRemainingSeatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRemainingSeatsReply) ProtoMessage() {}

func (x *CountRemainingSeatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seat_seat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRemainingSeatsReply.ProtoReflect.Descriptor instead.
func (*CountRemainingSeatsReply) Descriptor() ([]byte, []int) {
	return file_proto_seat_seat_proto_rawDescGZIP(), []int{1}
}

func (x *CountRemainingSeatsReply) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetSeatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatType       uint32 `protobuf:"fixed32,1,opt,name=SeatType,proto3" json:"SeatType,omitempty"`
	ScheduleStatus uint64 `protobuf:"fixed64,2,opt,name=ScheduleStatus,proto3" json:"ScheduleStatus,omitempty"`
	Number         uint32 `protobuf:"fixed32,3,opt,name=Number,proto3" json:"Number,omitempty"`
	TrainID        uint64 `protobuf:"fixed64,4,opt,name=TrainID,proto3" json:"TrainID,omitempty"`
}

func (x *GetSeatsRequest) Reset() {
	*x = GetSeatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seat_seat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsRequest) ProtoMessage() {}

func (x *GetSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seat_seat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetSeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_seat_seat_proto_rawDescGZIP(), []int{2}
}

func (x *GetSeatsRequest) GetSeatType() uint32 {
	if x != nil {
		return x.SeatType
	}
	return 0
}

func (x *GetSeatsRequest) GetScheduleStatus() uint64 {
	if x != nil {
		return x.ScheduleStatus
	}
	return 0
}

func (x *GetSeatsRequest) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GetSeatsRequest) GetTrainID() uint64 {
	if x != nil {
		return x.TrainID
	}
	return 0
}

type GetSeatsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool     `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
	SeatIDs   []uint64 `protobuf:"fixed64,2,rep,packed,name=SeatIDs,proto3" json:"SeatIDs,omitempty"`
}

func (x *GetSeatsReply) Reset() {
	*x = GetSeatsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seat_seat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSeatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatsReply) ProtoMessage() {}

func (x *GetSeatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seat_seat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatsReply.ProtoReflect.Descriptor instead.
func (*GetSeatsReply) Descriptor() ([]byte, []int) {
	return file_proto_seat_seat_proto_rawDescGZIP(), []int{3}
}

func (x *GetSeatsReply) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *GetSeatsReply) GetSeatIDs() []uint64 {
	if x != nil {
		return x.SeatIDs
	}
	return nil
}

type RollbackSeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatID         uint64 `protobuf:"fixed64,1,opt,name=SeatID,proto3" json:"SeatID,omitempty"`
	ScheduleStatus uint64 `protobuf:"fixed64,2,opt,name=ScheduleStatus,proto3" json:"ScheduleStatus,omitempty"`
}

func (x *RollbackSeatRequest) Reset() {
	*x = RollbackSeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seat_seat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackSeatRequest) ProtoMessage() {}

func (x *RollbackSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seat_seat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackSeatRequest.ProtoReflect.Descriptor instead.
func (*RollbackSeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_seat_seat_proto_rawDescGZIP(), []int{4}
}

func (x *RollbackSeatRequest) GetSeatID() uint64 {
	if x != nil {
		return x.SeatID
	}
	return 0
}

func (x *RollbackSeatRequest) GetScheduleStatus() uint64 {
	if x != nil {
		return x.ScheduleStatus
	}
	return 0
}

type RollbackSeatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
}

func (x *RollbackSeatReply) Reset() {
	*x = RollbackSeatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_seat_seat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackSeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackSeatReply) ProtoMessage() {}

func (x *RollbackSeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_seat_seat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackSeatReply.ProtoReflect.Descriptor instead.
func (*RollbackSeatReply) Descriptor() ([]byte, []int) {
	return file_proto_seat_seat_proto_rawDescGZIP(), []int{5}
}

func (x *RollbackSeatReply) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

var File_proto_seat_seat_proto protoreflect.FileDescriptor

var file_proto_seat_seat_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x74, 0x2f, 0x73, 0x65, 0x61,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x65, 0x61, 0x74, 0x22, 0x7a, 0x0a,
	0x1a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53,
	0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x08, 0x53,
	0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x49,
	0x44, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0e, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x32, 0x0a, 0x18, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x87, 0x01,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x07, 0x52, 0x08, 0x53, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x06, 0x52, 0x07,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x47, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x74, 0x49, 0x44,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x06, 0x52, 0x07, 0x53, 0x65, 0x61, 0x74, 0x49, 0x44, 0x73,
	0x22, 0x55, 0x0a, 0x13, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x06, 0x53, 0x65, 0x61, 0x74, 0x49, 0x44, 0x12,
	0x26, 0x0a, 0x0e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x31, 0x0a, 0x11, 0x52, 0x6f, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xe1, 0x01, 0x0a, 0x04, 0x53,
	0x65, 0x61, 0x74, 0x12, 0x59, 0x0a, 0x13, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x61, 0x74, 0x73, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x61,
	0x74, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73,
	0x65, 0x61, 0x74, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x38,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x73, 0x65, 0x61,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x61, 0x74, 0x12, 0x19, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e,
	0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0c,
	0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x73, 0x65, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_seat_seat_proto_rawDescOnce sync.Once
	file_proto_seat_seat_proto_rawDescData = file_proto_seat_seat_proto_rawDesc
)

func file_proto_seat_seat_proto_rawDescGZIP() []byte {
	file_proto_seat_seat_proto_rawDescOnce.Do(func() {
		file_proto_seat_seat_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_seat_seat_proto_rawDescData)
	})
	return file_proto_seat_seat_proto_rawDescData
}

var file_proto_seat_seat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_seat_seat_proto_goTypes = []interface{}{
	(*CountRemainingSeatsRequest)(nil), // 0: seat.CountRemainingSeatsRequest
	(*CountRemainingSeatsReply)(nil),   // 1: seat.CountRemainingSeatsReply
	(*GetSeatsRequest)(nil),            // 2: seat.GetSeatsRequest
	(*GetSeatsReply)(nil),              // 3: seat.GetSeatsReply
	(*RollbackSeatRequest)(nil),        // 4: seat.RollbackSeatRequest
	(*RollbackSeatReply)(nil),          // 5: seat.RollbackSeatReply
}
var file_proto_seat_seat_proto_depIdxs = []int32{
	0, // 0: seat.Seat.CountRemainingSeats:input_type -> seat.CountRemainingSeatsRequest
	2, // 1: seat.Seat.GetSeats:input_type -> seat.GetSeatsRequest
	4, // 2: seat.Seat.RollbackSeat:input_type -> seat.RollbackSeatRequest
	1, // 3: seat.Seat.CountRemainingSeats:output_type -> seat.CountRemainingSeatsReply
	3, // 4: seat.Seat.GetSeats:output_type -> seat.GetSeatsReply
	5, // 5: seat.Seat.RollbackSeat:output_type -> seat.RollbackSeatReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_seat_seat_proto_init() }
func file_proto_seat_seat_proto_init() {
	if File_proto_seat_seat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_seat_seat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountRemainingSeatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seat_seat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountRemainingSeatsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seat_seat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSeatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seat_seat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSeatsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seat_seat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollbackSeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_seat_seat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollbackSeatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_seat_seat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_seat_seat_proto_goTypes,
		DependencyIndexes: file_proto_seat_seat_proto_depIdxs,
		MessageInfos:      file_proto_seat_seat_proto_msgTypes,
	}.Build()
	File_proto_seat_seat_proto = out.File
	file_proto_seat_seat_proto_rawDesc = nil
	file_proto_seat_seat_proto_goTypes = nil
	file_proto_seat_seat_proto_depIdxs = nil
}
