// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: proto/train/train.proto

package train

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetStationListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InitialName string `protobuf:"bytes,1,opt,name=InitialName,proto3" json:"InitialName,omitempty"`
}

func (x *GetStationListRequest) Reset() {
	*x = GetStationListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_train_train_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationListRequest) ProtoMessage() {}

func (x *GetStationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_train_train_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationListRequest.ProtoReflect.Descriptor instead.
func (*GetStationListRequest) Descriptor() ([]byte, []int) {
	return file_proto_train_train_proto_rawDescGZIP(), []int{0}
}

func (x *GetStationListRequest) GetInitialName() string {
	if x != nil {
		return x.InitialName
	}
	return ""
}

type Station struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	StationName string `protobuf:"bytes,2,opt,name=StationName,proto3" json:"StationName,omitempty"`
}

func (x *Station) Reset() {
	*x = Station{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_train_train_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Station) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Station) ProtoMessage() {}

func (x *Station) ProtoReflect() protoreflect.Message {
	mi := &file_proto_train_train_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Station.ProtoReflect.Descriptor instead.
func (*Station) Descriptor() ([]byte, []int) {
	return file_proto_train_train_proto_rawDescGZIP(), []int{1}
}

func (x *Station) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Station) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

type GetStationListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationList []*Station `protobuf:"bytes,1,rep,name=StationList,proto3" json:"StationList,omitempty"`
}

func (x *GetStationListReply) Reset() {
	*x = GetStationListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_train_train_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStationListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationListReply) ProtoMessage() {}

func (x *GetStationListReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_train_train_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationListReply.ProtoReflect.Descriptor instead.
func (*GetStationListReply) Descriptor() ([]byte, []int) {
	return file_proto_train_train_proto_rawDescGZIP(), []int{2}
}

func (x *GetStationListReply) GetStationList() []*Station {
	if x != nil {
		return x.StationList
	}
	return nil
}

type SearchStationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *SearchStationRequest) Reset() {
	*x = SearchStationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_train_train_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStationRequest) ProtoMessage() {}

func (x *SearchStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_train_train_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStationRequest.ProtoReflect.Descriptor instead.
func (*SearchStationRequest) Descriptor() ([]byte, []int) {
	return file_proto_train_train_proto_rawDescGZIP(), []int{3}
}

func (x *SearchStationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SearchStationReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationList []*Station `protobuf:"bytes,1,rep,name=StationList,proto3" json:"StationList,omitempty"`
}

func (x *SearchStationReply) Reset() {
	*x = SearchStationReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_train_train_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchStationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStationReply) ProtoMessage() {}

func (x *SearchStationReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_train_train_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStationReply.ProtoReflect.Descriptor instead.
func (*SearchStationReply) Descriptor() ([]byte, []int) {
	return file_proto_train_train_proto_rawDescGZIP(), []int{4}
}

func (x *SearchStationReply) GetStationList() []*Station {
	if x != nil {
		return x.StationList
	}
	return nil
}

type GetScheduleListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheduleID int64 `protobuf:"varint,1,opt,name=ScheduleID,proto3" json:"ScheduleID,omitempty"`
}

func (x *GetScheduleListRequest) Reset() {
	*x = GetScheduleListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_train_train_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScheduleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleListRequest) ProtoMessage() {}

func (x *GetScheduleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_train_train_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleListRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleListRequest) Descriptor() ([]byte, []int) {
	return file_proto_train_train_proto_rawDescGZIP(), []int{5}
}

func (x *GetScheduleListRequest) GetScheduleID() int64 {
	if x != nil {
		return x.ScheduleID
	}
	return 0
}

type Schedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID               int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TrainNo          int64  `protobuf:"varint,2,opt,name=TrainNo,proto3" json:"TrainNo,omitempty"`
	TrainType        int64  `protobuf:"varint,3,opt,name=TrainType,proto3" json:"TrainType,omitempty"`
	StartTime        string `protobuf:"bytes,4,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime          string `protobuf:"bytes,5,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Duration         string `protobuf:"bytes,6,opt,name=Duration,proto3" json:"Duration,omitempty"`
	StartStationName string `protobuf:"bytes,7,opt,name=StartStationName,proto3" json:"StartStationName,omitempty"`
	EndStationName   string `protobuf:"bytes,8,opt,name=EndStationName,proto3" json:"EndStationName,omitempty"`
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_train_train_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_train_train_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_proto_train_train_proto_rawDescGZIP(), []int{6}
}

func (x *Schedule) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Schedule) GetTrainNo() int64 {
	if x != nil {
		return x.TrainNo
	}
	return 0
}

func (x *Schedule) GetTrainType() int64 {
	if x != nil {
		return x.TrainType
	}
	return 0
}

func (x *Schedule) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Schedule) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Schedule) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Schedule) GetStartStationName() string {
	if x != nil {
		return x.StartStationName
	}
	return ""
}

func (x *Schedule) GetEndStationName() string {
	if x != nil {
		return x.EndStationName
	}
	return ""
}

type GetScheduleListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheduleList []*Schedule `protobuf:"bytes,1,rep,name=ScheduleList,proto3" json:"ScheduleList,omitempty"`
}

func (x *GetScheduleListReply) Reset() {
	*x = GetScheduleListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_train_train_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScheduleListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleListReply) ProtoMessage() {}

func (x *GetScheduleListReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_train_train_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleListReply.ProtoReflect.Descriptor instead.
func (*GetScheduleListReply) Descriptor() ([]byte, []int) {
	return file_proto_train_train_proto_rawDescGZIP(), []int{7}
}

func (x *GetScheduleListReply) GetScheduleList() []*Schedule {
	if x != nil {
		return x.ScheduleList
	}
	return nil
}

type GetStopsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheduleID int64 `protobuf:"varint,1,opt,name=ScheduleID,proto3" json:"ScheduleID,omitempty"`
}

func (x *GetStopsRequest) Reset() {
	*x = GetStopsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_train_train_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStopsRequest) ProtoMessage() {}

func (x *GetStopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_train_train_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStopsRequest.ProtoReflect.Descriptor instead.
func (*GetStopsRequest) Descriptor() ([]byte, []int) {
	return file_proto_train_train_proto_rawDescGZIP(), []int{8}
}

func (x *GetStopsRequest) GetScheduleID() int64 {
	if x != nil {
		return x.ScheduleID
	}
	return 0
}

type Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NO               int64  `protobuf:"varint,1,opt,name=NO,proto3" json:"NO,omitempty"`
	StartTime        string `protobuf:"bytes,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime          string `protobuf:"bytes,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Duration         int64  `protobuf:"varint,4,opt,name=Duration,proto3" json:"Duration,omitempty"`
	StartStationName string `protobuf:"bytes,6,opt,name=StartStationName,proto3" json:"StartStationName,omitempty"`
	EndStationName   string `protobuf:"bytes,7,opt,name=EndStationName,proto3" json:"EndStationName,omitempty"`
}

func (x *Stop) Reset() {
	*x = Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_train_train_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_train_train_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_proto_train_train_proto_rawDescGZIP(), []int{9}
}

func (x *Stop) GetNO() int64 {
	if x != nil {
		return x.NO
	}
	return 0
}

func (x *Stop) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Stop) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Stop) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Stop) GetStartStationName() string {
	if x != nil {
		return x.StartStationName
	}
	return ""
}

func (x *Stop) GetEndStationName() string {
	if x != nil {
		return x.EndStationName
	}
	return ""
}

type GetStopsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stops []*Stop `protobuf:"bytes,1,rep,name=stops,proto3" json:"stops,omitempty"`
}

func (x *GetStopsReply) Reset() {
	*x = GetStopsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_train_train_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStopsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStopsReply) ProtoMessage() {}

func (x *GetStopsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_train_train_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStopsReply.ProtoReflect.Descriptor instead.
func (*GetStopsReply) Descriptor() ([]byte, []int) {
	return file_proto_train_train_proto_rawDescGZIP(), []int{10}
}

func (x *GetStopsReply) GetStops() []*Stop {
	if x != nil {
		return x.Stops
	}
	return nil
}

var File_proto_train_train_proto protoreflect.FileDescriptor

var file_proto_train_train_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x22, 0x39, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x07, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x30, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x28, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x46, 0x0a, 0x12, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x30, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x44, 0x22, 0xfa, 0x01,
	0x0a, 0x08, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x4e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x4e, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x45, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x45, 0x6e, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4b, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x33, 0x0a, 0x0c, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x0c, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x6f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x44, 0x22, 0xbe, 0x01, 0x0a, 0x04, 0x53,
	0x74, 0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x4e, 0x4f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x4e, 0x4f, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x45, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x45, 0x6e, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x21, 0x0a, 0x05,
	0x73, 0x74, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x32,
	0xad, 0x02, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x4c, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x12,
	0x16, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_train_train_proto_rawDescOnce sync.Once
	file_proto_train_train_proto_rawDescData = file_proto_train_train_proto_rawDesc
)

func file_proto_train_train_proto_rawDescGZIP() []byte {
	file_proto_train_train_proto_rawDescOnce.Do(func() {
		file_proto_train_train_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_train_train_proto_rawDescData)
	})
	return file_proto_train_train_proto_rawDescData
}

var file_proto_train_train_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_train_train_proto_goTypes = []interface{}{
	(*GetStationListRequest)(nil),  // 0: train.GetStationListRequest
	(*Station)(nil),                // 1: train.Station
	(*GetStationListReply)(nil),    // 2: train.GetStationListReply
	(*SearchStationRequest)(nil),   // 3: train.SearchStationRequest
	(*SearchStationReply)(nil),     // 4: train.SearchStationReply
	(*GetScheduleListRequest)(nil), // 5: train.GetScheduleListRequest
	(*Schedule)(nil),               // 6: train.Schedule
	(*GetScheduleListReply)(nil),   // 7: train.GetScheduleListReply
	(*GetStopsRequest)(nil),        // 8: train.GetStopsRequest
	(*Stop)(nil),                   // 9: train.Stop
	(*GetStopsReply)(nil),          // 10: train.GetStopsReply
}
var file_proto_train_train_proto_depIdxs = []int32{
	1,  // 0: train.GetStationListReply.StationList:type_name -> train.Station
	1,  // 1: train.SearchStationReply.StationList:type_name -> train.Station
	6,  // 2: train.GetScheduleListReply.ScheduleList:type_name -> train.Schedule
	9,  // 3: train.GetStopsReply.stops:type_name -> train.Stop
	0,  // 4: train.train.GetStationList:input_type -> train.GetStationListRequest
	3,  // 5: train.train.SearchStation:input_type -> train.SearchStationRequest
	5,  // 6: train.train.GetScheduleList:input_type -> train.GetScheduleListRequest
	8,  // 7: train.train.GetStops:input_type -> train.GetStopsRequest
	2,  // 8: train.train.GetStationList:output_type -> train.GetStationListReply
	4,  // 9: train.train.SearchStation:output_type -> train.SearchStationReply
	7,  // 10: train.train.GetScheduleList:output_type -> train.GetScheduleListReply
	10, // 11: train.train.GetStops:output_type -> train.GetStopsReply
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_train_train_proto_init() }
func file_proto_train_train_proto_init() {
	if File_proto_train_train_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_train_train_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStationListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_train_train_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Station); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_train_train_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStationListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_train_train_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchStationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_train_train_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchStationReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_train_train_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScheduleListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_train_train_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Schedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_train_train_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScheduleListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_train_train_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStopsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_train_train_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_train_train_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStopsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_train_train_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_train_train_proto_goTypes,
		DependencyIndexes: file_proto_train_train_proto_depIdxs,
		MessageInfos:      file_proto_train_train_proto_msgTypes,
	}.Build()
	File_proto_train_train_proto = out.File
	file_proto_train_train_proto_rawDesc = nil
	file_proto_train_train_proto_goTypes = nil
	file_proto_train_train_proto_depIdxs = nil
}
