// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/userAPI/userAPI.proto

package userAPI

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserAPI service

func NewUserAPIEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserAPI service

type UserAPIService interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterReply, error)
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginReply, error)
}

type userAPIService struct {
	c    client.Client
	name string
}

func NewUserAPIService(name string, c client.Client) UserAPIService {
	return &userAPIService{
		c:    c,
		name: name,
	}
}

func (c *userAPIService) Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterReply, error) {
	req := c.c.NewRequest(c.name, "UserAPI.Register", in)
	out := new(RegisterReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAPIService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginReply, error) {
	req := c.c.NewRequest(c.name, "UserAPI.Login", in)
	out := new(LoginReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserAPI service

type UserAPIHandler interface {
	Register(context.Context, *RegisterRequest, *RegisterReply) error
	Login(context.Context, *LoginRequest, *LoginReply) error
}

func RegisterUserAPIHandler(s server.Server, hdlr UserAPIHandler, opts ...server.HandlerOption) error {
	type userAPI interface {
		Register(ctx context.Context, in *RegisterRequest, out *RegisterReply) error
		Login(ctx context.Context, in *LoginRequest, out *LoginReply) error
	}
	type UserAPI struct {
		userAPI
	}
	h := &userAPIHandler{hdlr}
	return s.Handle(s.NewHandler(&UserAPI{h}, opts...))
}

type userAPIHandler struct {
	UserAPIHandler
}

func (h *userAPIHandler) Register(ctx context.Context, in *RegisterRequest, out *RegisterReply) error {
	return h.UserAPIHandler.Register(ctx, in, out)
}

func (h *userAPIHandler) Login(ctx context.Context, in *LoginRequest, out *LoginReply) error {
	return h.UserAPIHandler.Login(ctx, in, out)
}
